#!/usr/bin/env ruby

# cli frontend for the Netscaler REST API
#

require_relative 'apihandler.rb'
require_relative 'configfiles.rb'





# setup the netscaler objects
api = NSLBApiHandler.new("wh")
api.callrest_login




