#!/usr/bin/env ruby

# cli frontend for the Netscaler REST API
#

require_relative 'resthandler.rb'



# setup the netscaler objects and call the login
rest = NSLBRestHandler.new("wh")
rest.call_rest_login

#rest.call_rest_getlbvstats

rest.call_rest_create("lbvserver")
