#!/usr/bin/env ruby

# cli frontend for the Netscaler REST API
#

require_relative 'resthandler.rb'



# setup the netscaler objects
rest = NSLBRestHandler.new("wh")
rest.call_rest_login
rest.call_rest_getlbvstats

# this doesn't actually pull cs vserver stats
#rest.call_rest_getcsvstats



