#!/usr/bin/env ruby

# cli frontend for the Netscaler REST API
#

require_relative 'resthandler.rb'



# initiate the netscaler objects and call the login
rest = NSLBRestHandler.new("wh","dev","","","chuck.hilyard","","rundeckdemo")




#rest.call_rest_getlbvstats
#rest.call_rest_delete





# create a LB object
#
# arguments
# ssl or nonssl - if ssl is required further setup will be required.   
#   add ssl cs vserver
#   bind cs vserver certkeyName
#   bind ssl cipherName
# content switching server required? - this one is more complicated as it's shared.
# site specific? {wh, lax, iad, ams, syd, nrt}
# platform specific? {usa, can, eur, gbr, aus, jpn}
# environment {dev, qa, stg, prod}  
#
# order of operations and requirements
#
# add server FQDN FQDN
# add lbvserver NAME (IP address if standalone) 
# add serviceGroup NAME 
# add lb monitor NAME ("GET /project/health/up")
# add cs policy NAME (STARTSWITH "/project/")
# bind serviceGroup NAME SERVER PORT
# bind servcieGroup NAME -monitorName NAME
# bind cs vserver NAME -policName NAME -targetLBVserver NAME numb++
rest.call_rest_create("nonssl","no","wh","usa","dev")
